name: Build and Push Docker Image

on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Read version from file
      id: vars
      run: |
        commit_message="${{ github.event.head_commit.message }}"
        if [[ $commit_message =~ release\ staging\ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
          version="${BASH_REMATCH[1]}"
          echo "version=$version" >> $GITHUB_ENV
          echo "VERSION=$version"
        else
          echo "No version found in the commit message."
          exit 1
        fi
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          sapeled3/nj-releaseplease:staging-${{ env.version }}
          sapeled3/nj-releaseplease:latest
