name: Release please staging

on:
  push:
    branches:
      - production

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: python
          # optional. customize path to release-please-config.json
          config-file: relese-please/prod/release-please-prod-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: relese-please/prod/.release-please-prod-manifest.json
