name: Release please pseudo production

on:
  push:
    branches:
    - pseudo_production

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v4
      with:
        target-branch: pseudo_production
        # this assumes that you have created a personal access token
        # (PAT) and configured it as a GitHub action secret named
        # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
        token: ${{ secrets.GITHUB_TOKEN }}
        # optional. customize path to release-please-config.json
        config-file: relese-please/pseudo_prod/release-please-config.json
        # optional. customize path to .release-please-manifest.json
        manifest-file: relese-please/pseudo_prod/.release-please-manifest.json
